# Description: Tasks Library
---
version: 1
task_templates:
# Create external tables needed for benchmark
- id: setup
  files:
  - src/main/resources/scripts/tpch/setup/spark/ddl-external-tables.sql
# Create data maintenance external tables needed for benchmark
- id: setup_data_maintenance
  files:
  - src/main/resources/scripts/tpch/setup_data_maintenance/spark/ddl-external-tables-refresh.sql
  parameter_values_file: src/main/resources/auxiliary/tpch/setup_data_maintenance/parameter_values.dat
# Create schema and drop existing tables
- id: init
  files:
  - src/main/resources/scripts/tpch/init/spark/init.sql
# Create benchmark tables and load data into them
- id: build
  files:
  - src/main/resources/scripts/tpch/build/spark/1_create_customer.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_lineitem.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_nation.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_orders.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_part.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_partsupp.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_region.sql
  - src/main/resources/scripts/tpch/build/spark/1_create_supplier.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_customer.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_lineitem.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_nation.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_orders.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_part.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_partsupp.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_region.sql
  - src/main/resources/scripts/tpch/build/spark/2_load_supplier.sql
# Compute statistics for tables
- id: analyze
  files:
  - src/main/resources/scripts/tpch/build/spark/3_analyze_customer.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_lineitem.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_nation.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_orders.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_part.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_partsupp.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_region.sql
  - src/main/resources/scripts/tpch/build/spark/3_analyze_supplier.sql
# Execution of TPC-H queries
- id: single_user
  files:
  - src/main/resources/scripts/tpch/single_user/spark/query1.sql
  - src/main/resources/scripts/tpch/single_user/spark/query2.sql
  - src/main/resources/scripts/tpch/single_user/spark/query3.sql
  - src/main/resources/scripts/tpch/single_user/spark/query4.sql
  - src/main/resources/scripts/tpch/single_user/spark/query5.sql
  - src/main/resources/scripts/tpch/single_user/spark/query6.sql
  - src/main/resources/scripts/tpch/single_user/spark/query7.sql
  - src/main/resources/scripts/tpch/single_user/spark/query8.sql
  - src/main/resources/scripts/tpch/single_user/spark/query9.sql
  - src/main/resources/scripts/tpch/single_user/spark/query10.sql
  - src/main/resources/scripts/tpch/single_user/spark/query11.sql
  - src/main/resources/scripts/tpch/single_user/spark/query12.sql
  - src/main/resources/scripts/tpch/single_user/spark/query13.sql
  - src/main/resources/scripts/tpch/single_user/spark/query14.sql
  - src/main/resources/scripts/tpch/single_user/spark/query15.sql
  - src/main/resources/scripts/tpch/single_user/spark/query16.sql
  - src/main/resources/scripts/tpch/single_user/spark/query17.sql
  - src/main/resources/scripts/tpch/single_user/spark/query18.sql
  - src/main/resources/scripts/tpch/single_user/spark/query19.sql
  - src/main/resources/scripts/tpch/single_user/spark/query20.sql
  - src/main/resources/scripts/tpch/single_user/spark/query21.sql
  - src/main/resources/scripts/tpch/single_user/spark/query22.sql
# Execution of TPC-H data maintenance queries (RF1)
- id: data_maintenance_1
  files:
  - src/main/resources/scripts/tpch/data_maintenance/spark/RF1.sql
  parameter_values_file: src/main/resources/auxiliary/tpch/data_maintenance/parameter_values.dat
# Execution of TPC-H data maintenance queries (RF2)
- id: data_maintenance_2
  files:
  - src/main/resources/scripts/tpch/data_maintenance/spark/RF2.sql
  parameter_values_file: src/main/resources/auxiliary/tpch/data_maintenance/parameter_values.dat
